
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightPOWrightUMINUSDIVIDE LPAREN MINUS NUMBER PLUS POW RPAREN TIMESstatement : expressionexpression : expression PLUS termexpression : expression MINUS expression expression : MINUS expression %prec UMINUSexpression : termterm : term TIMES factorterm : term DIVIDE factorterm : factorfactor : NUMBERfactor : LPAREN expression RPARENexpression : expression POW termexpression : expression POW MINUS termterm : term DIVIDE MINUS factorterm : term TIMES MINUS factor'
    
_lr_action_items = {'MINUS':([0,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,19,21,23,24,25,26,],[4,9,-5,4,-8,-9,4,4,18,20,22,-4,9,-2,-3,-11,-6,-7,-10,-12,-14,-13,]),'NUMBER':([0,4,7,8,9,10,11,12,18,20,22,],[6,6,6,6,6,6,6,6,6,6,6,]),'LPAREN':([0,4,7,8,9,10,11,12,18,20,22,],[7,7,7,7,7,7,7,7,7,7,7,]),'$end':([1,2,3,5,6,13,15,16,17,19,21,23,24,25,26,],[0,-1,-5,-8,-9,-4,-2,-3,-11,-6,-7,-10,-12,-14,-13,]),'PLUS':([2,3,5,6,13,14,15,16,17,19,21,23,24,25,26,],[8,-5,-8,-9,-4,8,-2,-3,-11,-6,-7,-10,-12,-14,-13,]),'POW':([2,3,5,6,13,14,15,16,17,19,21,23,24,25,26,],[10,-5,-8,-9,-4,10,-2,10,-11,-6,-7,-10,-12,-14,-13,]),'RPAREN':([3,5,6,13,14,15,16,17,19,21,23,24,25,26,],[-5,-8,-9,-4,23,-2,-3,-11,-6,-7,-10,-12,-14,-13,]),'TIMES':([3,5,6,15,17,19,21,23,24,25,26,],[11,-8,-9,11,11,-6,-7,-10,11,-14,-13,]),'DIVIDE':([3,5,6,15,17,19,21,23,24,25,26,],[12,-8,-9,12,12,-6,-7,-10,12,-14,-13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,4,7,9,],[2,13,14,16,]),'term':([0,4,7,8,9,10,18,],[3,3,3,15,3,17,24,]),'factor':([0,4,7,8,9,10,11,12,18,20,22,],[5,5,5,5,5,5,19,21,5,25,26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','zad2.py',29),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','zad2.py',34),
  ('expression -> expression MINUS expression','expression',3,'p_expression_minus_expression','zad2.py',39),
  ('expression -> MINUS expression','expression',2,'p_expr_uminus','zad2.py',44),
  ('expression -> term','expression',1,'p_expression_term','zad2.py',49),
  ('term -> term TIMES factor','term',3,'p_term_times','zad2.py',53),
  ('term -> term DIVIDE factor','term',3,'p_term_div','zad2.py',58),
  ('term -> factor','term',1,'p_term_factor','zad2.py',68),
  ('factor -> NUMBER','factor',1,'p_factor_num','zad2.py',72),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','zad2.py',77),
  ('expression -> expression POW term','expression',3,'p_expression_pow','zad2.py',81),
  ('expression -> expression POW MINUS term','expression',4,'p_expression_pow_minus','zad2.py',85),
  ('term -> term DIVIDE MINUS factor','term',4,'p_expression_div_minus','zad2.py',91),
  ('term -> term TIMES MINUS factor','term',4,'p_expression_times_minus','zad2.py',97),
]
